### ISSUE TITLE
[FEAT] - Add Link to Docs

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/issues-list#4]
### What feature would you like to see?

Somewhere in the header text (IDK where yet), we should add a link to the [contributing documentation](https://docs.nhcarrigan.com) - probably a link to our chat server as well.

**Comment by Azuremis** [comment]
Hi @nhcarrigan, I'd like to work on this

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by Azuremis** [comment]
@nhcarrigan I've tried searching for a file named Docs in this repo but nothing clear came up. Could you clarify which files need changing?

**Comment by nhcarrigan** [comment]
Sure!

We'd want to add a couple of links to the `main` component found [here](https://github.com/nhcarrigan/issues-list/blob/main/src/app/main/main.component.html). One link should point to the contributing documentation: `https://docs.nhcarrigan.com`, and one should point to the chat server: `https://chat.nhcarrigan.com`.

**Comment by Azuremis** [comment]
Thanks for the assistance, that makes sense. I think the links should go before the *Choose an organisation* text as it then feels more natural to have the filtering functionality you've built come after this from a user journey perspective. Does that sound good to you @nhcarrigan?

**Comment by nhcarrigan** [comment]
I think that's an excellent plan!
